version: '3'

services:

  database:
    image: postgres:latest
    container_name: postgress-db-sample
    volumes:
      - "db-data:/var/lib/postgresql/data"
    networks:
      - back-tier

  spring-boot-jdk11-gradle:
    image: com.ebusato/spring-boot-jdk11-gradle
    container_name: spring-boot-jdk11-gradle-sample
    depends_on:
      - database
    ports:
      - 8080:8080
    networks:
      - back-tier

  volumes:
    db-data:

  networks:
    back-tier: